name: Linux Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      
    - name: Add i386 architecture
      run: sudo dpkg --add-architecture i386

    - name: Update repository
      run: sudo apt-get update
      
    - name: Install build packages
      run: sudo apt-get -qq install -y build-essential gcc-multilib g++-multilib libc6-dev libc6-dev-i386

    - name: Install GCC 4.8.5
      run: |
        wget https://ftp.gnu.org/gnu/gcc/gcc-4.8.5/gcc-4.8.5.tar.bz2 --no-check-certificate
        tar xf gcc-4.8.5.tar.bz2
        sed -i -e 's/__attribute__/\/\/__attribute__/g' gcc-4.8.5/gcc/cp/cfns.h
        sed -i 's/struct ucontext/ucontext_t/g' gcc-4.8.5/libgcc/config/i386/linux-unwind.h
        mkdir xgcc-4.8.5
        pushd xgcc-4.8.5
        $PWD/../gcc-4.8.5/configure --enable-languages=c,c++ --prefix=/usr --enable-shared --enable-plugin --program-suffix=-4.8.5
        make MAKEINFO="makeinfo --force" -j
        sudo make install -j

    - name: Run build
      working-directory: ./MatchBot
      run: make
    
    - name: Move release file to publish
      run: |
        # Make Match BOT path
        mkdir -p publish/addons/matchbot/dlls

        # Move released file to dlls
        mv ./MatchBot/Release/matchbot_mm.so publish/addons/matchbot/dlls

        # Copy cstrike contents to publish dir
        cp -ar cstrike/. publish

    - name: Download metamod-r
      run: |
        # Get latest release version of metamod-r
        wget $(curl -s https://api.github.com/repos/theAsmodai/metamod-r/releases/latest | grep 'browser_' | cut -d\" -f4)

        # Unzip metamod library to metamod folder
        unzip -p metamod-bin*.zip addons/metamod/metamod_i386.so > publish/addons/metamod/metamod_i386.so

    - name: Download hitbox_fixer
      run: |
        # Get latest release version of hitbox_fixer
        wget $(curl -s https://api.github.com/repos/Garey27/hitbox_fixer/releases/latest | grep 'browser_' | cut -d\" -f4)

        # Unzip hitbox_fixer library to metamod folder
        unzip -p hitbox_fix-bin*.zip addons/hitbox_fix/hitbox_fix_mm_i386.so > publish/addons/hitbox_fix/hitbox_fix_mm_i386.so

    - name: Deploy artifacts
      uses: actions/upload-artifact@v3
      with:
        name: matchbot-linux
        path: publish/*