name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
      
    - name: Add i386 architecture
      run: sudo dpkg --add-architecture i386

    - name: Add new source into apt
      run: sudo sh -c "sudo echo 'deb http://dk.archive.ubuntu.com/ubuntu/ bionic main universe' >> /etc/apt/sources.list.d/ubuntu.universe.list"
      
    - name: Update repository
      run: sudo apt-get update
      
    - name: Install build dependencies
      run: apt-get install -y -qq --no-install-recommends gcc-multilib g++-multilib libstdc++6 lib32stdc++6 libc6-dev libc6-dev-i386 linux-libc-dev linux-libc-dev:i386 lib32z1-dev nasm gcc-6 g++6 g++-6-multilib

    - name: Run build
      working-directory: ./MatchBot
      run: make
    
    - name: Move files
      run: |
        mkdir -p publish/addons/matchbot/dlls
        mv ./MatchBot/Release/matchbot_mm.so publish/addons/matchbot/dlls
        cp -ar cstrike/. publish

    - name: Deploy artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux
        path: publish/*
