name: Linux Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      
    - name: Add i386 architecture
      run: sudo dpkg --add-architecture i386

    - name: Update repository
      run: sudo apt-get update
      
    - name: Install build dependencies
      run: sudo apt-get -qq install -y build-essential g++ gcc-multilib g++-multilib libc6-dev libc6-dev-i386

    - name: Get GCC 4.8.5 packages and install it
      run: |
        mkdir gcc_48_install
        cd gcc_48_install
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.8/gcc-4.8-base_4.8.5-4ubuntu8_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.8/g++-4.8_4.8.5-4ubuntu8_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.8/cpp-4.8_4.8.5-4ubuntu8_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.8/libasan0_4.8.5-4ubuntu8_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.8/libgcc-4.8-dev_4.8.5-4ubuntu8_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.8/libstdc++-4.8-dev_4.8.5-4ubuntu8_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.8/gcc-4.8-multilib_4.8.5-4ubuntu8_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.8/g++-4.8-multilib_4.8.5-4ubuntu8_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.8/gcc-4.8_4.8.5-4ubuntu8_amd64.deb

    - name: Install GCC 4.8.5 packages
      run: |
        cd gcc_48_install
        sudo dpkg -i ./gcc-4.8-base_4.8.5-4ubuntu8_amd64.deb
        sudo dpkg -i ./cpp-4.8_4.8.5-4ubuntu8_amd64.deb
        sudo dpkg -i ./libasan0_4.8.5-4ubuntu8_amd64.deb
        sudo dpkg -i ./libgcc-4.8-dev_4.8.5-4ubuntu8_amd64.deb
        sudo dpkg -i ./libstdc++-4.8-dev_4.8.5-4ubuntu8_amd64.deb
        sudo dpkg -i ./g++-4.8_4.8.5-4ubuntu8_amd64.deb
        sudo dpkg -i ./gcc-4.8-multilib_4.8.5-4ubuntu8_amd64.deb
        sudo dpkg -i ./g++-4.8-multilib_4.8.5-4ubuntu8_amd64.deb
        sudo dpkg -i ./gcc-4.8_4.8.5-4ubuntu8_amd64.deb

    - name: Update GCC 4.8.5 alternatives
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 48 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
        sudo update-alternatives --config gcc
        sudo update-alternatives --config g++

    - name: Run build
      working-directory: ./MatchBot
      run: make
    
    - name: Move release file to publish
      run: |
        # Make Match BOT path
        mkdir -p publish/addons/matchbot/dlls

        # Move released file to dlls
        mv ./MatchBot/Release/matchbot_mm.so publish/addons/matchbot/dlls

        # Copy cstrike contents to publish dir
        cp -ar cstrike/. publish

    - name: Download metamod-r
      run: |
        # Get latest release version of metamod-r
        wget $(curl -s https://api.github.com/repos/theAsmodai/metamod-r/releases/latest | grep 'browser_' | cut -d\" -f4)

        # Unzip metamod library to metamod folder
        unzip -p metamod-bin*.zip addons/metamod/metamod_i386.so > publish/addons/metamod/metamod_i386.so

    - name: Download hitbox_fixer
      run: |
        # Get latest release version of hitbox_fixer
        wget $(curl -s https://api.github.com/repos/Garey27/hitbox_fixer/releases/latest | grep 'browser_' | cut -d\" -f4)

        # Unzip hitbox_fixer library to metamod folder
        unzip -p hitbox_fix-bin*.zip addons/hitbox_fix/hitbox_fix_mm_i386.so > publish/addons/hitbox_fix/hitbox_fix_mm_i386.so

    - name: Deploy artifacts
      uses: actions/upload-artifact@v3
      with:
        name: matchbot-linux
        path: publish/*