name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
      
    - name: Add i386 architecture
      run: sudo dpkg --add-architecture i386

    - name: Add new source into apt
      run: sudo sh -c "sudo echo 'deb http://dk.archive.ubuntu.com/ubuntu/ bionic main universe' >> /etc/apt/sources.list.d/ubuntu.universe.list"
      
    - name: Update repository
      run: sudo apt-get update
      
    - name: Install build dependencies
      run: sudo apt-get install -qq -y build-essential g++-5-multilib g++-5 gcc-5

    - name: Run build
      working-directory: ./MatchBot
      run: make
    
    - name: Move files
      run: |
        mkdir -p publish/addons/matchbot/dlls
        mv ./MatchBot/Release/matchbot_mm.so publish/addons/matchbot/dlls
        cp -ar cstrike/. publish

    - name: Deploy artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux
        path: publish/*
