name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Add i386 architecture
      run: sudo dpkg --add-architecture i386

    - name: Update repository
      run: sudo apt-get update
      
    - name: Install build dependencies
      run: sudo apt-get install -qq -y build-essential g++ gcc-multilib g++-multilib

    - name: Run build
      working-directory: ./MatchBot
      run: make
    
    - name: Move release file
      run: |
        mkdir -p publish/addons/matchbot/dlls
        mv ./MatchBot/Release/matchbot_mm.so publish/addons/matchbot/dlls
        cp -ar cstrike/. publish

    - name: Deploy artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux
        path: publish/*
