name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: centos:7

    steps:
    - uses: actions/checkout@v3

    - name: Install build dependencies
      run: yes | yum -y --assumeyes install libgcc.i686 glibc.i686 glibc-devel.i686 libstdc++.i686 libstdc++-devel.i686 @'Development Tools'

    - name: Run build
      working-directory: ./MatchBot
      run: make

    - name: Move release file
      run: |
        mkdir -p publish/addons/matchbot/dlls
        mv ./MatchBot/Release/matchbot_mm.so publish/addons/matchbot/dlls
        cp -ar cstrike/. publish

    - name: Deploy artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux
        path: publish/*
