name: Linux Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: centos:7

    steps:
    - uses: actions/checkout@v3
      
    - name: Update cache
      run: yes | yum -y --assumeyes makecache

    - name: Install build dependencies
      run: yes | yum -y --assumeyes install @'Development Tools' wget glibc-devel.i686 libgcc.i686 libstdc++-devel.i686 libcurl-devel.i686 openssl-devel.i686

    - name: Run build
      working-directory: ./MatchBot
      run: |
        # Export compiler include path
        export CPATH=$CPATH:/usr/include/c++/4.8.5/i686-redhat-linux

        # Make build
        make
    
    - name: Move release file to publish
      run: |
        # Make Match BOT path
        mkdir -p publish/addons/matchbot/dlls

        # Move released file to dlls
        mv ./MatchBot/Release/matchbot_mm.so publish/addons/matchbot/dlls

        # Copy cstrike contents to publish dir
        cp -ar cstrike/. publish

    - name: Download metamod-r
      run: |
        # Get latest release version of metamod-r
        wget https://github.com/theAsmodai/metamod-r/releases/download/1.3.0.131/metamod-bin-1.3.0.131.zip

        # Unzip metamod library to metamod folder
        unzip -p metamod-bin*.zip addons/metamod/metamod_i386.so > publish/addons/metamod/metamod_i386.so

    - name: Download hitbox_fixer
      run: |
        # Get latest release version of hitbox_fixer
        wget https://github.com/Garey27/hitbox_fixer/releases/download/1.1.2/hitbox_fix-bin-1.1.2.zip

        # Unzip hitbox_fixer library to metamod folder
        unzip -p hitbox_fix-bin*.zip addons/hitbox_fix/hitbox_fix_mm_i386.so > publish/addons/hitbox_fix/hitbox_fix_mm_i386.so

    - name: Deploy artifacts
      uses: actions/upload-artifact@v3
      with:
        name: matchbot-linux
        path: publish/*