name: Linux Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: centos:7

    steps:
    - uses: actions/checkout@v3
      
    - name: Update cache
      run: yes | yum -y --assumeyes makecache

    - name: Install build dependencies
      run: yes | yum -y --assumeyes install @'Development Tools' glibc-devel.i686 libgcc.i686 libstdc++-devel.i686

    - name: Run test
      run: |
        g++ --version
        gcc --version
        echo | gcc -E -Wp,-v -
        echo | cpp -xc++ -Wp,-v

    - name: Deploy artifacts
      uses: actions/upload-artifact@v3
      with:
        name: matchbot-linux
        path: publish/*