name: Windows Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download metamod-r
      run: |
        wget $(curl -s https://api.github.com/repos/theAsmodai/metamod-r/releases/latest | grep 'browser_' | cut -d="\"" -f4)
        unzip -p metamod-bin*.zip addons/metamod/metamod.dll > publish/addons/metamod/metamod.dll

    - name: Deploy artifacts
      uses: actions/upload-artifact@main
      with:
        name: matchbot-windows
        path: publish/*
