name: Windows Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download metamod-r
      run: |
        curl -s https://api.github.com/repos/theAsmodai/metamod-r/releases/latest |
        grep "browser_download_url.*.zip"  |
        cut -d : -f 2,3  |
        tr -d "'" |
        Invoke-WebRequest -Uri -

    - name: Expand metamod-r
      run: |
        Expand-Archive metamod.zip addons/metamod/metamod.dll > publish/addons/metamod/metamod.dll
        dir

    - name: Deploy artifacts
      uses: actions/upload-artifact@main
      with:
        name: matchbot-windows
        path: publish/*
