name: Windows Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Run Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Move release file to publish
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        # Make publish directory
        mkdir publish\addons\matchbot\dlls

        # Move cstrike files to publish
        move ${{env.SOLUTION_FILE_PATH}}\cstrike publish

        # Move released dll to publish
        move ${{env.BUILD_CONFIGURATION}}\*.dll publish\addons\matchbot\dlls

    - name: Download Metamod-r
      run: |
        # Set Repository path
        $repoUrl = "https://api.github.com/repos/theAsmodai/metamod-r/releases/latest"

        # Set assets data
        $assets = ((Invoke-WebRequest $repoUrl | ConvertFrom-Json).assets | Where-Object name -like "metamod-bin-*.zip")

        # Get ZIP file name
        $zipName  = $assets.name

        # Download ZIP file
        Invoke-WebRequest -Uri $assets.browser_download_url -Out $zipName

        # Extract ZIP File
        Expand-Archive $zipName

        # Get base name from ZIP file
        $baseName = (Get-Item $zipName).BaseName

        # DLL from path
        $fromPath = ".\" + $baseName + "\addons\metamod\metamod.dll"

        # DLL dest path
        $DestPath = ".\publish\cstrike\addons\metamod\metamod.dll"
        
        # Copy item
        Copy-Item -Path $fromPath -Destination $DestPath

    - name: Deploy artifacts
      uses: actions/upload-artifact@main
      with:
        name: matchbot-windows
        path: publish/*
