name: Windows Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download Metamod-r
      run: |
        # Set Repository path
        $repoUrl = "https://api.github.com/repos/theAsmodai/metamod-r/releases/latest"

        # Set assets data
        $assets = ((Invoke-WebRequest $repoUrl | ConvertFrom-Json).assets | Where-Object name -like "metamod-bin-*.zip")

        # Get ZIP file name
        $zipName  = $assets.name

        # Download ZIP file
        Invoke-WebRequest -Uri $assets.browser_download_url -Out $zipName

        # Extract ZIP File
        Expand-Archive $zipName

        # Get base name from ZIP file
        $baseName = (Get-Item $zipName).BaseName

        # DLL from path
        $fromPath = ".\" + $baseName + "\addons\metamod\metamod.dll"

        # DLL dest path
        $DestPath = ".\publish\addons\metamod"
        
        # Copy item
        Copy-Item -Path $fromPath -Destination $DestPath

    - name: Deploy artifacts
      uses: actions/upload-artifact@main
      with:
        name: matchbot-windows
        path: publish/*
