name: Windows Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download metamod-r
      run: |
        Invoke-WebRequest -Uri ((Invoke-WebRequest "https://api.github.com/repos/theAsmodai/metamod-r/releases/latest" | ConvertFrom-Json).assets | Where-Object name -like "metamod-bin-*.zip").browser_download_url -Out metamod.zip
        Expand-Archive metamod.zip
        dir
        mkdir publish\addons\metamod
        Copy-Item -Path ".\addons\metamod\metamod.dll" -Destination ".\publish\addons\metamod"
        dir

    - name: Deploy artifacts
      uses: actions/upload-artifact@main
      with:
        name: matchbot-windows
        path: publish/*