name: Windows Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download Metamod-r
      run: |
        $repo   = "https://api.github.com/repos/theAsmodai/metamod-r/releases/latest"
        $assets = ((Invoke-WebRequest $repo | ConvertFrom-Json).assets | Where-Object name -like "metamod-bin-*.zip")
        $name   = $assets.name
        $url    = Invoke-WebRequest -Uri $assets.browser_download_url -Out $name
        Expand-Archive $name
        dir
#Copy-Item -Path ".\metamod\addons\metamod\metamod.dll" -Destination ".\publish\addons\metamod"

    - name: Deploy artifacts
      uses: actions/upload-artifact@main
      with:
        name: matchbot-windows
        path: publish/*
